### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by Atavic** [hacktoolspack/fsociety-ultra-sqli-scanner#1]
>'clear' is not recognized as an internal or external command,
operable program or batch file.

I get this on *cmd*, here's what I did:

1. extracted to folder
2. started as normal user 

After selecting *7* the same string appears, but then I get *Target IP ->* so it works.

I'm on XP.

**Comment by hacktoolspack** [comment]
startup error is fixed

**Comment by Atavic** [comment]
:+1: Seems better now.

But the extractor GUI is in french, while my OS is in english.

**Comment by hacktoolspack** [comment]
Yes the installation (If this is his whose you speak) Is in French because i am french. and I do not do no think that it disturbs. :-P

**Comment by Atavic** [comment]
:+1: Kein Problem.
